# default configuration with all args specified

# dataset arguments
data_dir: "/home/gmvincen/class_work/ece_542/Cross-lingual-SER/Dataset/ESD_preprocessed/"
source_dataset: "english_train"
target_dataset: "mandarin_test"

# output arguments
tensorboard_log_dir: "runs/"
model_path: "models/resnet50/"

# training arguments
model: "DANN"
encoder: "resnet50"
batch_size: 64
epochs: 30
lr: 0.0001
perturb: False 